spring:
  batch:
    job:
      names: ${job.name:NONE}
      enabled: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://localhost:3306/SAMPLE?characterEncoding=utf8&rewriteBatchedStatements=true&profileSQL=true
      driver-class-name: org.mariadb.jdbc.Driver
      username: USER
      password: ADMIN1
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 30000
      connection-timeout: 30000
      data-source-properties:
        rewriteBatchedStatements: true
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 1000
    database-platform: org.hibernate.dialect.MariaDB103Dialect
logging:
  level:
    root: INFO

#
sample:
  batch:
    version: v1